/**
 * Demo loom: a service-body accessory harness on a 12 V vehicle.
 *
 * Deliberately spans the whole current range so every branch of the calculation
 * gets exercised — a 0.5 A buzzer on the shop minimum gauge at one end, a 170 A
 * inverter feed on 1/0 with an ANL fuse at the other, and runs in between whose
 * size is forced by voltage drop rather than by current.
 *
 * Formboard coordinates are in millimetres on a 2400 x 1200 board, laid out the
 * way the harness is actually pinned down: battery box at the left, cab centre,
 * roof and rear accessories at the right.
 */

import type { Loom } from './types'

export const DEMO_LOOM: Loom = {
  id: 'demo-service-body',
  name: 'Service body accessory loom',
  description:
    'Inverter, dual DC-DC charging, roof lighting, central locking and cab alarm on a 12 V service body.',
  revision: 'A',
  settings: {
    systemVoltage_v: 12,
    ampacityBasis: 'sae_j1128',
    defaultFamily: 'awg',
    defaultAmbient_c: 30,
    defaultInsulationId: 'gxl',
    minimumSizeId: 'awg-20',
    serviceLoop_mm: 0,
  },
  formboard: { width_mm: 2400, height_mm: 1200 },
  nodes: [
    {
      id: 'bat',
      kind: 'source',
      name: 'Main battery +',
      location: 'Battery box, LH under-tray',
      position: { x: 60, y: 300 },
      formboardPosition: { x: 120, y: 600 },
      source: {
        nominalVoltage_v: 12,
        capacity_a: 300,
        batteryCapacity_ah: 210,
        description: '220 A alternator with a 210 Ah AGM auxiliary bank',
      },
    },
    {
      id: 'busbar',
      kind: 'splice',
      name: 'Positive distribution busbar',
      location: 'Battery box',
      position: { x: 220, y: 380 },
      formboardPosition: { x: 420, y: 760 },
      splice: { method: 'busbar', spliceId: 'busbar-stud' },
    },
    {
      id: 'inverter',
      kind: 'load',
      name: '2000 W inverter',
      location: 'Under-tray, LH rear',
      position: { x: 260, y: 120 },
      formboardPosition: { x: 480, y: 180 },
      load: {
        continuousCurrent_a: 170,
        duty: 'intermittent',
        dutyCyclePct: 60,
        description: '2000 W continuous at 12 V, 88 % efficiency',
      },
    },
    {
      id: 'dcdc50',
      kind: 'load',
      name: 'DC-DC charger, 50 A',
      location: 'Under-tray, LH forward',
      position: { x: 400, y: 470 },
      formboardPosition: { x: 760, y: 940 },
      load: { continuousCurrent_a: 50, duty: 'continuous', description: 'Auxiliary bank charger' },
    },
    {
      id: 'dcdc25',
      kind: 'load',
      name: 'DC-DC charger, 25 A',
      location: 'Under-tray, RH forward',
      position: { x: 400, y: 570 },
      formboardPosition: { x: 760, y: 1080 },
      load: { continuousCurrent_a: 25, duty: 'continuous', description: 'Starter battery maintainer' },
    },
    {
      id: 'fuseblock',
      kind: 'splice',
      name: '12-way accessory fuse block',
      location: 'Cab, behind LH kick panel',
      position: { x: 520, y: 300 },
      formboardPosition: { x: 1180, y: 600 },
      splice: { method: 'busbar' },
    },
    {
      id: 'dt2_lightbar',
      kind: 'connector',
      name: 'Roof light bar connector',
      location: 'Cab roof, LH A-pillar exit',
      position: { x: 720, y: 180 },
      formboardPosition: { x: 1780, y: 300 },
      connector: { seriesId: 'deutsch-dt', ways: 2, cavities: { '1': 'C-201 feed', '2': 'C-201 return' } },
    },
    {
      id: 'dtm2_strobe',
      kind: 'connector',
      name: 'Strobe connector',
      location: 'Cab roof, centre rear',
      position: { x: 720, y: 260 },
      formboardPosition: { x: 1780, y: 440 },
      connector: { seriesId: 'deutsch-dtm', ways: 2, cavities: { '1': 'C-202 feed', '2': 'C-202 return' } },
    },
    {
      id: 'lightbar',
      kind: 'load',
      name: 'LED light bar',
      location: 'Roof rack, front',
      position: { x: 880, y: 180 },
      formboardPosition: { x: 2180, y: 300 },
      load: {
        continuousCurrent_a: 10,
        inrushCurrent_a: 30,
        inrushDuration_ms: 20,
        duty: 'intermittent',
        dutyCyclePct: 30,
        description: '120 W LED bar, capacitive inrush at switch-on',
      },
    },
    {
      id: 'strobe',
      kind: 'load',
      name: 'Amber strobe beacon',
      location: 'Roof rack, rear',
      position: { x: 880, y: 260 },
      formboardPosition: { x: 2180, y: 440 },
      load: { continuousCurrent_a: 1, duty: 'continuous', description: 'LED rotating beacon' },
    },
    {
      id: 'buzzer',
      kind: 'load',
      name: 'Reverse buzzer',
      location: 'Rear crossmember',
      position: { x: 720, y: 380 },
      formboardPosition: { x: 1620, y: 760 },
      load: { continuousCurrent_a: 0.5, duty: 'momentary', description: 'Piezo reversing alarm' },
    },
    {
      id: 'locking',
      kind: 'load',
      name: 'Central locking actuators (x4)',
      location: 'Canopy doors, all four',
      position: { x: 720, y: 470 },
      formboardPosition: { x: 1620, y: 940 },
      load: {
        continuousCurrent_a: 5,
        inrushCurrent_a: 40,
        inrushDuration_ms: 250,
        duty: 'momentary',
        description: 'Four solenoid actuators, worst case all driven together',
      },
    },
    {
      id: 'gnd_cab',
      kind: 'splice',
      name: 'Cab ground splice',
      location: 'Cab, behind LH kick panel',
      position: { x: 620, y: 580 },
      formboardPosition: { x: 1180, y: 1080 },
      splice: { method: 'crimp', spliceId: 'splice-butt-1.5-2.5' },
    },
    {
      id: 'gnd_chassis',
      kind: 'ground',
      name: 'Chassis ground stud',
      location: 'Cab floor, LH sill, M8 stud',
      position: { x: 480, y: 660 },
      formboardPosition: { x: 820, y: 1160 },
      ground: { method: 'chassis', stud: 'M8' },
    },
    {
      id: 'gnd_bat',
      kind: 'ground',
      name: 'Battery negative post',
      location: 'Battery box, LH under-tray',
      position: { x: 60, y: 480 },
      formboardPosition: { x: 120, y: 1000 },
      ground: { method: 'battery', stud: 'M8' },
    },
  ],
  edges: [
    /* ---- high current, straight off the battery ---- */
    {
      id: 'e-inv-feed',
      fromNodeId: 'bat',
      toNodeId: 'inverter',
      circuitId: 'C-101',
      label: 'Inverter +',
      length_mm: 1200,
      class: 'power',
      returnPath: 'modeled',
      insulationId: 'battery_pvc',
      protection: { familyId: 'anl', holderId: 'holder-anl-inline' },
      notes: 'Fuse within 300 mm of the battery post.',
    },
    {
      id: 'e-inv-gnd',
      fromNodeId: 'inverter',
      toNodeId: 'gnd_bat',
      circuitId: 'C-101G',
      label: 'Inverter −',
      length_mm: 1200,
      class: 'ground',
      returnPath: 'modeled',
      insulationId: 'battery_pvc',
      // Matched to the positive feed. Shop convention: negative is cut from the
      // same reel as the positive on any run this size.
      gaugeOverrideId: 'awg-1-0',
    },

    /* ---- distribution ---- */
    {
      id: 'e-bat-bus',
      fromNodeId: 'bat',
      toNodeId: 'busbar',
      circuitId: 'C-100',
      label: 'Busbar feed',
      length_mm: 350,
      class: 'power',
      returnPath: 'modeled',
      insulationId: 'battery_pvc',
      protection: { familyId: 'mega', holderId: 'holder-mega-stud' },
    },
    {
      id: 'e-bus-dcdc50',
      fromNodeId: 'busbar',
      toNodeId: 'dcdc50',
      circuitId: 'C-110',
      label: 'DC-DC 50 A feed',
      length_mm: 800,
      class: 'charging',
      returnPath: 'modeled',
      protection: { familyId: 'midi', rating_a: 60, holderId: 'holder-midi-stud' },
      notes: 'Redarc FK60 input fuse kit.',
    },
    {
      id: 'e-dcdc50-gnd',
      fromNodeId: 'dcdc50',
      toNodeId: 'gnd_bat',
      circuitId: 'C-110G',
      length_mm: 800,
      class: 'ground',
      returnPath: 'modeled',
      gaugeOverrideId: 'awg-8',
    },
    {
      id: 'e-bus-dcdc25',
      fromNodeId: 'busbar',
      toNodeId: 'dcdc25',
      circuitId: 'C-120',
      label: 'DC-DC 25 A feed',
      length_mm: 900,
      class: 'charging',
      returnPath: 'modeled',
      protection: { familyId: 'midi', rating_a: 40, holderId: 'holder-midi-stud' },
      notes: 'Redarc FK40 input fuse kit.',
    },
    {
      id: 'e-dcdc25-gnd',
      fromNodeId: 'dcdc25',
      toNodeId: 'gnd_bat',
      circuitId: 'C-120G',
      length_mm: 900,
      class: 'ground',
      returnPath: 'modeled',
      gaugeOverrideId: 'awg-8',
    },
    {
      id: 'e-bus-fb',
      fromNodeId: 'busbar',
      toNodeId: 'fuseblock',
      circuitId: 'C-130',
      label: 'Cab fuse block feed',
      length_mm: 3200,
      class: 'power',
      returnPath: 'modeled',
      protection: { familyId: 'midi', holderId: 'holder-midi-stud' },
      bundleCount: 2,
      notes: 'Runs the length of the chassis rail into the cab.',
    },

    /* ---- cab and roof accessories ---- */
    {
      id: 'e-fb-lightbar',
      fromNodeId: 'fuseblock',
      toNodeId: 'dt2_lightbar',
      circuitId: 'C-201',
      label: 'Light bar feed',
      length_mm: 2400,
      class: 'power',
      returnPath: 'modeled',
      protection: { familyId: 'ato' },
      bundleCount: 4,
    },
    {
      id: 'e-dt-lightbar',
      fromNodeId: 'dt2_lightbar',
      toNodeId: 'lightbar',
      circuitId: 'C-201',
      length_mm: 400,
      class: 'power',
      returnPath: 'modeled',
      // Same gauge as the feed so C-201 is one reel on the cut list.
      gaugeOverrideId: 'awg-14',
    },
    {
      id: 'e-fb-strobe',
      fromNodeId: 'fuseblock',
      toNodeId: 'dtm2_strobe',
      circuitId: 'C-202',
      label: 'Strobe feed',
      length_mm: 2600,
      class: 'power',
      returnPath: 'modeled',
      protection: { familyId: 'ato' },
      bundleCount: 4,
    },
    {
      id: 'e-dtm-strobe',
      fromNodeId: 'dtm2_strobe',
      toNodeId: 'strobe',
      circuitId: 'C-202',
      length_mm: 300,
      class: 'power',
      returnPath: 'modeled',
    },
    {
      id: 'e-fb-buzzer',
      fromNodeId: 'fuseblock',
      toNodeId: 'buzzer',
      circuitId: 'C-203',
      label: 'Reverse buzzer',
      length_mm: 600,
      class: 'signal',
      returnPath: 'modeled',
      protection: { familyId: 'ato' },
      bundleCount: 4,
    },
    {
      id: 'e-fb-locking',
      fromNodeId: 'fuseblock',
      toNodeId: 'locking',
      circuitId: 'C-204',
      label: 'Central locking',
      length_mm: 1800,
      class: 'power',
      returnPath: 'modeled',
      protection: { familyId: 'ato' },
      bundleCount: 4,
    },

    /* ---- returns ---- */
    {
      id: 'e-lightbar-gnd',
      fromNodeId: 'lightbar',
      toNodeId: 'gnd_cab',
      circuitId: 'C-201G',
      length_mm: 2800,
      class: 'ground',
      returnPath: 'modeled',
      bundleCount: 4,
    },
    {
      id: 'e-strobe-gnd',
      fromNodeId: 'strobe',
      toNodeId: 'gnd_cab',
      circuitId: 'C-202G',
      length_mm: 2900,
      class: 'ground',
      returnPath: 'modeled',
      bundleCount: 4,
    },
    {
      id: 'e-buzzer-gnd',
      fromNodeId: 'buzzer',
      toNodeId: 'gnd_cab',
      circuitId: 'C-203G',
      length_mm: 600,
      class: 'ground',
      returnPath: 'modeled',
      bundleCount: 4,
    },
    {
      id: 'e-locking-gnd',
      fromNodeId: 'locking',
      toNodeId: 'gnd_cab',
      circuitId: 'C-204G',
      length_mm: 1800,
      class: 'ground',
      returnPath: 'modeled',
      bundleCount: 4,
      gaugeOverrideId: 'awg-18',
    },
    {
      id: 'e-gndcab-chassis',
      fromNodeId: 'gnd_cab',
      toNodeId: 'gnd_chassis',
      circuitId: 'C-200G',
      label: 'Cab ground strap',
      length_mm: 500,
      class: 'ground',
      returnPath: 'modeled',
    },
  ],
}
